version: '3'
services:
  flash-memorizer-app:
    container_name: flash-memorizer-db
    image: flash-memorizer:1.2.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FlashMemorizer
      - MYSQL_ROOT_HOST=%
    ports:
      - "8001:8001"
    volumes:
      - flash-memorizer-data:/var/lib/mysql

  flash-memorizer-db:
    container_name: flash-memorizer-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FlashMemorizer
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - flash-memorizer-data:/var/lib/mysql

volumes:
  flash-memorizer-data: