version: '3.8'
services:
  flash-memorizer-app:
    container_name: flash-memorizer-app
    image: vananne/flash-memorizer:2.0
    environment:
      PROD_DB_URL: flash-memorizer-db:5432/FlashMemorizer
      PROD_DB_USER: root
      PROD_DB_PASSWORD: root
      PROD_MAIL_EMAIL: vanantran009@gmail.com
      PROD_MAIL_PASSWORD: slqohvgrgtqkftbp
    ports:
      - "8001:8001"
    networks:
      - flash-memorizer-net
    depends_on:
      flash-memorizer-db:
        condition: service_healthy

  flash-memorizer-db:
    container_name: flash-memorizer-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=FlashMemorizer
    ports:
      - "5432:5432"
    volumes:
      - flash-memorizer-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d FlashMemorizer || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - flash-memorizer-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "83:80"
    depends_on:
      - flash-memorizer-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - flash-memorizer-net

volumes:
  flash-memorizer-data:

networks:
  flash-memorizer-net:
    driver: bridge