server:
  port: 8000

spring:
  application:
    name: flash-memorizer-app

  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://containers-us-west-94.railway.app:8054/railway
    username: root
    password: r6KRegMsyRmNwx9jEyd8
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

api:
  voiceRssApiUrl: https://api.voicerss.org/
  voiceRssApiKey: d62e7c8089e446bc84849496b4dc5f5f