version: '3.8'
services:
  flash-memorizer-db:
    image: postgres:latest
    container_name: flash-memorizer-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FlashMemorizer
    ports:
      - "5432:5432"
    volumes:
      - flash-memorizer-data:/var/lib/postgresql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "83:80"
    depends_on:
      - flash-memorizer-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork

volumes:
  flash-memorizer-data:

networks:
  pgnetwork:
    driver: bridge